gripper_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

gripper_controller:
  type: effort_controllers/JointGroupPositionController
  joints: 
    - hande_left_finger_joint
    - hande_right_finger_joint

  hande_left_finger_joint: 
    pid: {p: 0.1, i: 0.0, d: 1.0}
  hande_right_finger_joint: 
    pid: {p: 0.1, i: 0.0, d: 1.0}